global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9091"]
  - job_name: "jenkins"
    metrics_path: /prom/
    static_configs:
      - targets: ["host.docker.internal:49000"]
